a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalnum())
print('É Alfanumerico?', a.isalpha())
print('Está em maiuscula?',a.isupper())
print('Está em minuscula?', a.islower())
print('Éstá capitalizado?', a.capitalize())

