nome = str(input('Digite seu nome completo:')).strip()
print('Analisando seu nome...')
print('seu nome em maiusculas é {}.'.format(nome.upper()))
print('seu nome em minusculas é {}'.format(nome.lower()))
print('seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))